print('Hello ini script python')
print()

print('{0:>16}'.format('*'))
print('{0:>17}'.format('***'))
print('{0:>18}'.format('*****'))
print('{0:>19}'.format('*******'))
print('{0:>20}'.format('*********'))
print('{0:>19}'.format('*******'))
print('{0:>18}'.format('*****'))
print('{0:>17}'.format('***'))
print('{0:>16}'.format('*'))
